
package:
  name: gridtools
  version: 0.4.1

source:
  git_url: https://github.com/CAB-LAB/gridtools.git
#  git_rev: v0.4.0rc0+1

build:
  number: 0

requirements:
  build:
    # use build variant : https://conda.io/docs/user-guide/tasks/build-packages/variants.html
    - python {{ python }}
    - numpy {{ numpy }}
    - numba {{ numba }}

  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - numba {{ numba }}

# todo - tests only failed in Windows build, must investigate
test:
  imports:
    - gridtools
    - gridtools.resampling
    - gridtools.gapfilling

about:
  home: https://github.com/CAB-LAB/gridtools
  license: MIT
  license_file: LICENSE

