name: gridtools
channels:
    - conda-forge
    - numba
    - anaconda
dependencies:
    - python ==3.6
    - numpy=1.13.1=py36_0
    - numba=0.35.0=np113py36_0
    #
    # for testing only
    #
    - pytest
    - pytest-cov