name: gridtools
channels:
    - conda-forge
    - numba
    - anaconda
dependencies:
    - python ==3.5
    - numpy=1.11.3=py35_0
    - numba=0.28.1=np111py35_0
    #
    # for testing only
    #
    - pytest
    - pytest-cov